baseURL = "https://kwon.nyc/"
languageCode = "en-us"
title = "Kwon.nyc"
theme = "kwon-theme"
publishDir = "public"
enableRobotsTXT = false
timeZone = "America/New_York"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "notes"
name = "Notes"
url = "/notes/"
weight = 20

[[menu.main]]
identifier = "photos"
name = "Photos â†—"
url = "https://kwon.photos/"
weight = 30

[params]
  mainSections = ['notes']
  assetDir = "assets"
  author = "Rachel J. Kwon"
  feed_token = "x5DA7Gxf8FnCFnDe"

[minification]
  enable = true

[markup.goldmark.renderer]
  unsafe = true